apiVersion: apps/v1
kind: Deployment
metadata:
  name: sryfvza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sryfvza
  template:
    metadata:
      labels:
        app: sryfvza
    spec:
      containers:
      - image: okteto.dev/sryfvza:latest
        name: sryfvza
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a31aa65e-6827-49bd-9854-e139d77cd938"
        - name: Vless_Path
          value: "/vl5edtuf66"
        - name: Vmess_UUID
          value: "a31aa65e-6827-49bd-9854-e139d77cd938"
        - name: Vmess_Path
          value: "/vmsr5sry7"
        - name: Share_Path
          value: "/v2link"
